#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.bak

cp /etc/hosts ~/hosts.new
sed -i '/127.*localhost/c\127.0.0.2 localhost' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

sudo cp -f ~/hosts.new /etc/hosts

echo "Updated /etc/hosts:"
cat /etc/hosts
