#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

sudo cp /etc/hosts /etc/hosts.bak

sudo sed -i '/127\.0\.0\.1\s\+localhost/d' /etc/hosts
sudo sed -i '/127\.0\.0\.2\s\+localhost/d' /etc/hosts
sudo sed -i '/facebook\.com/d' /etc/hosts

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

echo "Updated /etc/hosts:"
cat /etc/hosts
